# Generated by Django 3.0.5 on 2020-04-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectors', '0005_lector_numperpart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lector',
            old_name='numperpart',
            new_name='numberPart',
        ),
        migrations.RenameField(
            model_name='lector',
            old_name='shortinfo',
            new_name='shortInfo',
        ),
    ]
