# Generated by Django 3.0.5 on 2020-04-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectors', '0007_auto_20200419_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='numberPart',
            field=models.CharField(default='null', max_length=60, verbose_name='Номер главы'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='shortInfo',
            field=models.TextField(default='null', max_length=500, verbose_name='Краткая информация'),
        ),
    ]
