# Generated by Django 3.0.5 on 2020-04-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectors', '0009_auto_20200419_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lector',
            old_name='image',
            new_name='lectors1/',
        ),
    ]
