# Generated by Django 3.0.5 on 2020-04-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectors', '0014_auto_20200419_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='media/lectors1/',
        ),
        migrations.AddField(
            model_name='lector',
            name='image',
            field=models.ImageField(default='null', upload_to='lectors1/', verbose_name='Изображение'),
        ),
    ]
