# Generated by Django 3.0.5 on 2020-04-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectors', '0015_auto_20200419_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='image',
            field=models.ImageField(default='null', upload_to='lectors/', verbose_name='Изображение'),
        ),
    ]
