# Generated by Django 3.0.5 on 2020-04-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectors', '0017_lectorimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='image',
        ),
    ]
