# Generated by Django 3.0.5 on 2020-04-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectors', '0018_remove_lector_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
    ]
