# Generated by Django 3.0.5 on 2020-04-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectors', '0019_lector_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название лекции'),
        ),
    ]
