# Generated by Django 3.0.5 on 2020-05-02 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectors', '0020_auto_20200429_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectorTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectors.Lector', verbose_name='Лекция')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.AlterField(
            model_name='lectorimages',
            name='description',
            field=models.TextField(default=None, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='LectorTestQeustion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер вопроса')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('lectorTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectors.LectorTest', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы теста',
            },
        ),
    ]
