# Generated by Django 3.0.5 on 2020-05-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectors', '0021_auto_20200502_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LectorTestQeustion',
            new_name='LectorTestQuestion',
        ),
    ]
