# Generated by Django 3.0.5 on 2020-05-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectors', '0022_auto_20200502_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectortestquestion',
            name='lectorTest',
        ),
        migrations.DeleteModel(
            name='LectorTest',
        ),
        migrations.DeleteModel(
            name='LectorTestQuestion',
        ),
    ]
