# Generated by Django 3.0.5 on 2020-06-17 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectors', '0023_auto_20200503_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('shortInfo', models.TextField(default='Напишите сюда текст', verbose_name='Информация')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название вопроса')),
                ('answer', models.CharField(max_length=100, verbose_name='Ответ')),
                ('answer1', models.CharField(max_length=100, verbose_name='Ответ')),
                ('answer_true', models.CharField(max_length=100, verbose_name='Правильный ответ')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectors.Test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопросы для теста',
                'verbose_name_plural': 'Вопросы для теста',
            },
        ),
    ]
