# Generated by Django 3.0.5 on 2020-06-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectors', '0024_test_testquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='url',
            field=models.SlugField(default='Ponimanie', max_length=160, unique=True),
        ),
    ]
