# Generated by Django 3.0.5 on 2020-06-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectors', '0025_test_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestions',
            name='test',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestQuestions',
        ),
    ]
